controller_manager:
  ros__parameters:
    update_rate: 200

    wheel_effort_controller:
      type: effort_controllers/JointGroupEffortController

    leg_effort_controller:
      type: effort_controllers/JointGroupEffortController

wheel_effort_controller:
  ros__parameters:
    joints:
      - wheel_1_joint
      - wheel_2_joint

leg_effort_controller:
  ros__parameters:
    joints:
      - big_arm_1_joint
      - big_arm_2_joint
      - big_arm_3_joint
      - big_arm_4_joint
