controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    wheel_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    leg_effort_controller:
      type: effort_controllers/JointGroupEffortController


wheel_velocity_controller:
  ros__parameters:
    joints:
      - wheel_1_joint
      - wheel_2_joint
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity


leg_effort_controller:
  ros__parameters:
    joints:
      - big_arm_1_joint
      - big_arm_2_joint
      - big_arm_3_joint
      - big_arm_4_joint
